// src/db/schema/artworks.ts
import {
  boolean,
  date,
  integer,
  numeric,
  pgTable,
  serial,
  text,
  timestamp,
} from 'drizzle-orm/pg-core'
import { contacts } from './contacts'

export const artworks = pgTable('artworks', {
  id: serial('id').primaryKey(),
  sourcePieceId: integer('source_piece_id').unique(),
  title: text('title'),
  inventoryNumber: text('inventory_number'),
  type: text('type'),
  medium: text('medium'),
  subjectMatter: text('subject_matter'),
  height: numeric('height'),
  width: numeric('width'),
  depth: numeric('depth'),
  dimensionOverride: text('dimension_override'),
  weight: numeric('weight'),
  framed: boolean('framed').notNull().default(false),
  framedHeight: numeric('framed_height'),
  framedWidth: numeric('framed_width'),
  framedDepth: numeric('framed_depth'),
  paperHeight: numeric('paper_height'),
  paperWidth: numeric('paper_width'),
  creationYear: integer('creation_year'),
  creationDateCirca: boolean('creation_date_circa').notNull().default(false),
  creationDateOverride: text('creation_date_override'),
  description: text('description'),
  notes: text('notes'),
  signed: boolean('signed').notNull().default(false),
  signatureNotes: text('signature_notes'),
  condition: text('condition'),
  conditionNotes: text('condition_notes'),
  edition: text('edition'),
  editionInfo: text('edition_info'),
  attribution: text('attribution'),
  isPublic: boolean('is_public').notNull().default(false),
  purchaseDate: date('purchase_date'),
  purchasePrice: numeric('purchase_price'),
  purchaseCurrency: text('purchase_currency'),
  sourcePurchaseLocationId: integer('source_purchase_location_id'),
  purchaseLocationName: text('purchase_location_name'),
  sellerContactId: integer('seller_contact_id').references(() => contacts.id),
  purchaseUrl: text('purchase_url'),
  fairMarketValue: numeric('fair_market_value'),
  insuranceValue: numeric('insurance_value'),
  provenanceNotes: text('provenance_notes'),
  source: text('source'),
  currentLocationName: text('current_location_name'),
  sourceCurrentLocationId: integer('source_current_location_id'),
  currentSubLocationName: text('current_sub_location_name'),
  currentTertiaryLocationName: text('current_tertiary_location_name'),
  currentLocationStartDate: date('current_location_start_date'),
  currentLocationEndDate: date('current_location_end_date'),
  currentLocationNotes: text('current_location_notes'),
  currentLocationLatitude: numeric('current_location_latitude'),
  currentLocationLongitude: numeric('current_location_longitude'),
  lastUpdated: timestamp('last_updated'),
  lastUpdatedBy: text('last_updated_by'),
  dateAdded: date('date_added'),
})
