// src/db/schema/contacts.ts
import {
  boolean,
  date,
  integer,
  pgTable,
  serial,
  text,
} from 'drizzle-orm/pg-core'

export const contacts = pgTable('contacts', {
  id: serial('id').primaryKey(),
  sourceContactId: integer('source_contact_id').unique(),
  title: text('title'),
  firstName: text('first_name'),
  lastName: text('last_name'),
  email: text('email'),
  secondaryEmail: text('secondary_email'),
  jobTitle: text('job_title'),
  companyName: text('company_name'),
  workPhone: text('work_phone'),
  phone: text('phone'),
  mobilePhone: text('mobile_phone'),
  website: text('website'),
  birthDate: date('birth_date'),
  deathDate: date('death_date'),
  nationality: text('nationality'),
  address1: text('address1'),
  address2: text('address2'),
  city: text('city'),
  state: text('state'),
  zip: text('zip'),
  country: text('country'),
  secondaryAddress1: text('secondary_address1'),
  secondaryAddress2: text('secondary_address2'),
  secondaryCity: text('secondary_city'),
  secondaryState: text('secondary_state'),
  secondaryZip: text('secondary_zip'),
  secondaryCountry: text('secondary_country'),
  isArtist: boolean('is_artist').notNull().default(false),
  bio: text('bio'),
  notes: text('notes'),
  location: text('location'),
  sourceLocationId: integer('source_location_id'),
  instagramUrl: text('instagram_url'),
  dateAdded: date('date_added'),
})
