CREATE TABLE "contacts" (
	"id" serial PRIMARY KEY NOT NULL,
	"source_contact_id" integer,
	"title" text,
	"first_name" text,
	"last_name" text,
	"email" text,
	"secondary_email" text,
	"job_title" text,
	"company_name" text,
	"work_phone" text,
	"phone" text,
	"mobile_phone" text,
	"website" text,
	"birth_date" date,
	"death_date" date,
	"nationality" text,
	"address1" text,
	"address2" text,
	"city" text,
	"state" text,
	"zip" text,
	"country" text,
	"secondary_address1" text,
	"secondary_address2" text,
	"secondary_city" text,
	"secondary_state" text,
	"secondary_zip" text,
	"secondary_country" text,
	"is_artist" boolean DEFAULT false NOT NULL,
	"bio" text,
	"notes" text,
	"location" text,
	"source_location_id" integer,
	"instagram_url" text,
	"date_added" date,
	CONSTRAINT "contacts_source_contact_id_unique" UNIQUE("source_contact_id")
);
