CREATE TABLE "artworks" (
	"id" serial PRIMARY KEY NOT NULL,
	"source_piece_id" integer,
	"title" text,
	"inventory_number" text,
	"type" text,
	"medium" text,
	"subject_matter" text,
	"height" numeric,
	"width" numeric,
	"depth" numeric,
	"dimension_override" text,
	"weight" numeric,
	"framed" boolean DEFAULT false NOT NULL,
	"framed_height" numeric,
	"framed_width" numeric,
	"framed_depth" numeric,
	"paper_height" numeric,
	"paper_width" numeric,
	"creation_year" integer,
	"creation_date_circa" boolean DEFAULT false NOT NULL,
	"creation_date_override" text,
	"description" text,
	"notes" text,
	"signed" boolean DEFAULT false NOT NULL,
	"signature_notes" text,
	"condition" text,
	"condition_notes" text,
	"edition" text,
	"edition_info" text,
	"attribution" text,
	"is_public" boolean DEFAULT false NOT NULL,
	"purchase_date" date,
	"purchase_price" numeric,
	"purchase_currency" text,
	"source_purchase_location_id" integer,
	"purchase_location_name" text,
	"seller_contact_id" integer,
	"purchase_url" text,
	"fair_market_value" numeric,
	"insurance_value" numeric,
	"provenance_notes" text,
	"source" text,
	"current_location_name" text,
	"source_current_location_id" integer,
	"current_sub_location_name" text,
	"current_tertiary_location_name" text,
	"current_location_start_date" date,
	"current_location_end_date" date,
	"current_location_notes" text,
	"current_location_latitude" numeric,
	"current_location_longitude" numeric,
	"last_updated" timestamp,
	"last_updated_by" text,
	"date_added" date,
	CONSTRAINT "artworks_source_piece_id_unique" UNIQUE("source_piece_id")
);
--> statement-breakpoint
ALTER TABLE "artworks" ADD CONSTRAINT "artworks_seller_contact_id_contacts_id_fk" FOREIGN KEY ("seller_contact_id") REFERENCES "public"."contacts"("id") ON DELETE no action ON UPDATE no action;